title: HearMe service status page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: PWA Application
      description: Visit scheduling with integrated Chat / Video
      link: https://app.hearme.pl
    - name: WebRTC Video subsystem
      description: P2P Video Authorization API
    - name: SMS notification
      description: SMS notification subsystem (for therpists)
    - name: Phone access
      description: Public Switched Telephony Network conferencing subsystem (AUDIO visits)
    - name: Helpdesk
      description: Our company technical support phone line
      link: +48 22 153 05 50
    - name: Corporate website
      description: Our company public facing website
      link: https://hearme.pl
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/uploads/hmlogosq128.png
  description_header: Information about <a class='text-grey-darkest' title='Visit
    hearme.pl' href='https://hearme.pl/'>HearMe</a> systems operations.<br
    />Follow us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://twitter.com/hearme_eu'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  copyrightHolder: HearMe Sp. z o.o.
  eventsPerPage: 10
  iconType: image/png
  groups:
    - CoreServices
    - AdditionalServices
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit hearme.pl'
    href='https://hearme.pl/'>HearMe.pl</a> provides mental health related
    services to emploees.
